### ISSUE TITLE
Change Hapi dependency version

### ISSUE THREAD

**Issue by roman0x58** [Salesflare/hapi-auth-bearer-simple#53]
Hi. Please update Hapi version to 14.x.x to avoid **UNMET PEER DEPENDENCY** warnings. API seems wasn't changed.

**Comment by AdriVanHoudt** [comment]
Version 14 is indeed the same as version 13.5 but was re-released as 14 due to joi 9. I will update this asap

**Comment by AdriVanHoudt** [comment]
Fixed with https://github.com/Salesflare/hapi-auth-bearer-simple/commit/369267e2726f5d01dd0724a8efd373a7ec1f0f87 (forgot to mention issue in commit message :P ) and released a patch version
