### ISSUE TITLE
Unknown authentication strategy: bearer in path 

### ISSUE THREAD

**Issue by LovikaJain** [Salesflare/hapi-auth-bearer-simple#69]
I am trying to use this module to enable bearer token on my app. However, I am getting the error shown in the title.

I am trying to implement this module to enable token authorisation in my app But I am getting error mentioned below 
`e:\python_training\Training\Node\Test\Project\Backend\node_modules\hapi\node_modules\hoek\lib\index.js:723`

I have a route file 
```
`module.exports = [
    {
        method: 'GET',
        path: '/api/{_id?}',
        handler: function (request, reply) {
           Controller.control.get(request.params, function (err, success) {
                console.log(request.params);
                if (err) {  
                    reply(unifunc.sendError(err));
                } else {
                    reply(unifunc.sendSuccess(SuccessMsg,success)).code(200);
                }
            });
        },
        config: {
            description: 'desc',
            tags: ['api', 'oV'],
            validate: {
                headers: unifunc.authorizationHeaderObj,
                params: {
                    o_id: Joi.string().required().trim(),
                    _id: Joi.string().optional().trim()
                },
                failAction: unifunc.failActionFunction
            },
            auth: {
                strategy: 'bearer',
                scope: ['admin', 'user-{params.id}']
                },
            plugins: {
                'hapi-swagger': {
                    responseMessages: msgs
                }](url)

```

and a controller file in which I mentioned strategy 
```
var bearerSimple= require('hapi-auth-bearer-simple')
authorization = Authorization.auth; // This plugin has the logic to validate the token and return the error in case it fails and I am passing accesstoken as parameter in a function in that file
var getV = function(server, params, callbackRoute){  
    server.register(
        [{
            register: bearerSimple
        }], function(err){
     if(err){
         console.log("Failed to log the plugin",err);
         throw err;
     }
     server.auth.strategy('bearer', 'bearerAuth', {
        authorization : authorization
     });
    });
    console.log(params);
    async.series([
        function(cb){}
        ]}

```
The error message is:
```
Error: Unknown authentication strategy: bearer in path: /api/orders/{order_id}/vehicles/{_id?}
    at Object.exports.assert (e:\python_training\Training\Node\Test\Project\Backend\node_modules\hapi\node_modules\hoek\lib\index.js:723:11)
    at e:\python_training\Training\Node\Test\Project\Backend\node_modules\hapi\lib\auth.js:152:14
    at Array.forEach (native)
    at internals.Auth._setupRoute (e:\python_training\Training\Node\Test\Project\Backend\node_modules\hapi\lib\auth.js:149:24)
    at new module.exports.internals.Route (e:\python_training\Training\Node\Test\Project\Backend\node_modules\hapi\lib\route.js:142:47)
    at internals.Connection._addRoute (e:\python_training\Training\Node\Test\Project\Backend\node_modules\hapi\lib\connection.js:375:17)
    at internals.Connection._route (e:\python_training\Training\Node\Test\Project\Backend\node_modules\hapi\lib\connection.js:367:18)
    at wrappedRoute [as _route] (e:\python_training\Training\Node\Test\Project\Backend\node_modules\newrelic\lib\instrumentation\hapi.js:222:29)
    at internals.Plugin._apply (e:\python_training\Training\Node\Test\Project\Backend\node_modules\hapi\lib\plugin.js:460:14)
    at internals.Plugin.route 

 Is there any way I can resolve this issue?

**Comment by LovikaJain** [comment]
I placed strategy in server.js 
```
var validationFunction = Authorization.auth;
console.log(validationFunction);

server.register(
    [{
        register: bearerSimple
    }], function(err){
 if(err){
     console.log("Failed to log the plugin",err);
     throw err;
 }

 server.auth.strategy('bearer', 'bearerAuth', {
    validationFunction : validationFunction
 });
});

```
and in Authorization file looks like this 

```
function rauth(accessToken, cb) {
    var criteria = {accessToken: accessToken};
    var projection = {};
    var options = {limit: 1};
    Service.AdminService.getadmin(criteria, projection, options, function (err, data) {
        if (err) {
            cb(err);
        } else if (data && data.length > 0 && data[0]._id) {
            console.log(data);
            console.log(data.length);
            adminId = data[0]._id;
            cb()
        } else {
            cb(UniversalFunctions.CONFIG.APP_CONSTANTS.STATUS_MSG.ERROR.INVALID_ACCESS_TOKEN);
        }
    });
```
Now I am getting this error:

`
Error: options.validateFunc must be a valid function in bearerAuthentication scheme`

**Comment by AdriVanHoudt** [comment]
Can you `console.log(typeof Authorization.auth)`? Also in your example the function is called `rauth` not `auth` so maybe a typo?

**Comment by AdriVanHoudt** [comment]
I don't see the difference between what you have and the default test case :/
https://github.com/Salesflare/hapi-auth-bearer-simple/blob/89124127b1e28df8062f5e877e69b6818a38b8b7/test/index.js#L27-L67

Could you make a gist or something that errors with you that I can easily test?

**Comment by LovikaJain** [comment]
I found the problem it was with the function name I was using validationFunction : validationFunction in strategy. Changed it to validateFunction : validationFunction and now no errors but it is not reading the accessToken and not even going to the function while executing it.

171005/202050.614, [response], http://DESKTOP-02KCUJ9:3000: [1;32mget /api/orders/595fbf63ddb918253f4bd7e3/vehicles {} 401 (216ms) 

 Could I mail you the file with the endpoint which I am trying?

**Comment by AdriVanHoudt** [comment]
Oh totally missed that 😱 
Your validation function needs to callback like `callback(/*error, isValid, credential*/)`
As far as I can see you never callback with `callback(null, true, admin)` so it will never registers as authenticated.

**Comment by LovikaJain** [comment]
Thanks that worked. and Will it create any conflict if create multiple strategies ?

**Comment by AdriVanHoudt** [comment]
Just create not, if you want to chain them read https://hapijs.com/api#serverauthschemename-scheme

**Comment by LovikaJain** [comment]
Can I get the user details who is logged in while I am passing the accesstoken? I want to display the user details

**Comment by LovikaJain** [comment]
Can I get the user details from this? I need to get the logged in user Id and name

**Comment by AdriVanHoudt** [comment]
so when you callback using `callback(null, true, { id: 1, name: 'Doe' })` You will get access to the user credentials via `request.auth.credentials`. In this case `request.auth.credentials` will be `{ id: 1, name: 'Doe' }`

**Comment by LovikaJain** [comment]
But I am not passing the credentials to the callback function. I am returning an object data which contains user details along with id and name.

**Comment by LovikaJain** [comment]
Thanks pulled the credentials from the data itself :)

**Comment by AdriVanHoudt** [comment]
Glad you figured it out! 👍
