### ISSUE TITLE
Hapijs v17 compatible

### ISSUE THREAD

**Issue by razrabotchik** [Salesflare/hapi-auth-bearer-simple#96]
Is this plugin compatible with hapijs v17 ?
How can I integrate it to hapijs v17?

**Comment by AdriVanHoudt** [comment]
As you can see in the package.json it is not atm (https://github.com/Salesflare/hapi-auth-bearer-simple/blob/3ce25f445ac0f378e8f87fa7660641b35a9a20b0/package.json#L32)
We would love a PR for hapi 17 compatibility. I think it is updating the `register` interface and then how the plugin replies.
Tbh we now also use https://github.com/hapijs/hapi-auth-basic which is compatible with hapi 17 and does a tiny bit more. So maybe just look there?
